#!/usr/bin/env bash
# Install and configure HAProxy on lb-01
sudo apt update
sudo apt install haproxy -y

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg <<EOF 
frontend web_traffic
  bind *:80
  default_backend web_servers

backend web_servers
  balance roundrobin
  server web-01 3.84.222.117:80 check
  server web-02 34.207.253.96:80 check
EOF

#Enable and Start the HAProxy Service
sudo systemctl enable haproxy
sudo systemctl start haproxy
