#!/usr/bin/env bash
# Install HAproxy
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4
sudo apt-get -y update
sudo apt-get install -y haproxy=2.4.\*
echo "ENABLED=1" > /etc/default/haproxy
# listen to web1 and web2 servers
echo "
	listen load_balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 850-web-01 3.84.222.117:80 check
	server 850-web-02 34.207.253.96:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
